[sdl]
fullscreen=false
output=default
autolock=false

[render]
aspect=true
scaler=normal3x

[dosbox]
machine=cga

[cpu]
cputype=8086
cycles=fixed 1000

[autoexec]
mount c "E:\Projects\DOS Games\Karateka\karateka"
c:
karateka.exe
