[log]
logfile=E:\Projects\DOS Games\Karateka\karateka\docs\findings\dosboxx_test.log
int21=true
fileio=true
exec=true
files=true
keyboard=normal
debuggerrun=normal

[autoexec]
mount c "E:\Projects\DOS Games\Karateka\karateka"
c:
dir
exit
