[sdl]
fullscreen=false
fulldouble=false
output=surface

[dosbox]
machine=cga
captures=docs\findings\dosbox_captures

[render]
frameskip=0
aspect=true
scaler=normal2x

[cpu]
core=auto
cycles=3000
cycleup=500
cycledown=500

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[speaker]
pcspeaker=true
tandy=auto
disney=true

[autoexec]
mount a "E:\Projects\DOS Games\Karateka\karateka" -t floppy
a:
karateka.exe
