[sdl]
fullscreen=false
fulldouble=false
waitonerror=false
mapperfile=mapper-dosbox-x.map

[dosbox]
machine=cga
captures=docs\findings\dosboxx_captures

[log]
logfile=E:\Projects\DOS Games\Karateka\karateka\docs\findings\dosboxx_runtime.log
int21=true
fileio=true
exec=true
files=true
ioctl=true
dosmisc=normal
int10=normal
keyboard=normal
pit=normal
io=normal
debuggerrun=normal

[render]
frameskip=0
aspect=true
scaler=normal2x

[cpu]
core=normal
cputype=auto
cycles=3000

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[speaker]
pcspeaker=true
tandy=auto
disney=true

[dos]
xms=false
ems=false
umb=false

[autoexec]
mount a "E:\Projects\DOS Games\Karateka\karateka" -t floppy
a:
karateka.exe
